#!/usr/bin/env python3
"""
Script Writer Module for YouTube Scraper Agent
Takes a researched topic and writes a complete video script.
"""

from datetime import datetime
from pathlib import Path

OUTPUT_DIR = Path("/root/.openclaw/workspace/projects/youtube-scraper-agent")


def write_script(topic: str, angle: str, key_points: list, target_duration: int = 10):
    """
    Write a complete YouTube video script.
    
    Args:
        topic: The video topic/title
        angle: Your unique take/positioning
        key_points: List of 3-5 main points to cover
        target_duration: Target video length in minutes
    """
    
    # Calculate word count target (150 words per minute)
    target_words = target_duration * 150
    words_per_point = target_words // (len(key_points) + 2)  # +2 for intro and outro
    
    script = f"""# Video Script: {topic}

**Angle:** {angle}
**Target Duration:** {target_duration} minutes
**Target Words:** ~{target_words}
**Generated:** {datetime.now().strftime('%Y-%m-%d')}

---

## 🎬 HOOK (First 30 seconds)

*[Visual: High-energy shot or pattern interrupt]*

**Line 1 (Curiosity Gap):**
"I spent 6 months trying to [common struggle], and I discovered something that changed everything..."

**Line 2 (Credibility + Promise):**
"In the next {target_duration} minutes, I'm going to show you exactly how I [achieved result] — and how you can do it too, even if you're starting from zero."

**Line 3 (Pattern Interrupt):**
"But first, let me show you why everything you've been told about [topic] is actually backwards..."

*[Cut to B-roll or screen recording]*

---

## 📖 INTRO (30 seconds - 1 minute)

"So here's the thing. [State the problem/pain point in relatable terms].

I was [describe your situation before]. I tried [common solution 1], I tried [common solution 2], and honestly? Nothing worked.

Until I found [your solution/angle].

And in this video, I'm breaking down:
"

*[Bullet points on screen:]*
"""
    
    for i, point in enumerate(key_points, 1):
        script += f"- {point}\n"
    
    script += f"""
Plus, I'll share the [specific tactic] that [impressive result].

Let's dive in.

---

"""
    
    # Main content sections
    for i, point in enumerate(key_points, 1):
        script += f"""## 🎯 POINT {i}: {point.upper()}

*[Visual: Screen recording, demo, or relevant B-roll]*

"Okay, so first — {point}.

Here's what most people get wrong: [common misconception].

The reality is [your insight/angle]. Let me show you what I mean...

[Explain the concept with specific example]

**Key takeaway:** [One sentence summary they can remember]

---

"""
    
    script += f"""## 💡 THE TACTIC (Bonus Section)

*[Visual: Step-by-step walkthrough]*

"Now, I promised you the tactic that [result]. Here it is:

**Step 1:** [Action]
**Step 2:** [Action]
**Step 3:** [Action]

The key here is [critical insight]. Most people miss this because [reason].

But if you do this [timeframe], you'll see [expected outcome].

---

## 🎯 CTA / OUTRO (30 seconds)

"So that's exactly how I [achieved result] — and how you can too.

If you found this helpful, here's what to do next:

1. **Hit subscribe** — I post [frequency] about [topic focus]
2. **Comment below** with your biggest takeaway — I read every single one
3. **Watch this next:** [Related video recommendation]

Thanks for watching, and I'll see you in the next one.

---

## 🖼️ THUMBNAIL CONCEPT

**Visual:** [Describe the image — facial expression, background, props]

**Text Overlay:**
- Line 1: "[Short punchy phrase]"
- Line 2: "[Number or result]"

**Color Scheme:** [High contrast colors]

**Thumbnail Formula:** [Face/Pattern] + [Big Number] + [Curiosity Gap]

---

## 📝 NOTES FOR RECORDING

- **Tone:** Conversational, like explaining to a friend
- **Pacing:** Pause after key points for emphasis
- **Visuals:** Cut every 3-5 seconds to maintain energy
- **B-Roll:** Stock footage of [relevant scenes]
- **Music:** Upbeat instrumental, fade during speaking

## 🏷️ SUGGESTED TAGS

{', '.join([f'{topic.lower()}', 'tutorial', 'how to', 'guide', 'tips', 'strategy', 'beginner'])}

## 📊 SUCCESS METRICS TO TRACK

- CTR target: 8%+
- AVD target: 50%+
- Like rate: 4%+
- Comment rate: 1%+

---

*Script generated by YouTube Scraper Agent*
"""
    
    return script


def save_script(topic: str, script_content: str):
    """Save script to file."""
    # Clean filename
    clean_topic = "".join(c if c.isalnum() or c in (' ', '-') else '_' for c in topic)
    clean_topic = clean_topic.replace(' ', '-').lower()[:50]
    
    filename = f"script-{clean_topic}.md"
    filepath = OUTPUT_DIR / filename
    
    filepath.write_text(script_content)
    print(f"✅ Script saved: {filepath}")
    return filepath


# Example usage
if __name__ == "__main__":
    # Example: Generate a sample script
    example_topic = "How I Built a $5K/Month SaaS in 30 Days"
    example_angle = "The no-code, validation-first approach that actually works"
    example_points = [
        "Why most SaaS founders fail (and how to avoid it)",
        "The 7-day validation framework",
        "Building your MVP without writing code",
        "Getting your first 10 paying customers"
    ]
    
    script = write_script(example_topic, example_angle, example_points, target_duration=12)
    save_script(example_topic, script)
    print("\n🎬 Sample script generated!")
